// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7ACAZI6NYqpnmh1OB13rPT7wMrkXtO8',
    appId: '1:845349142321:web:21593d3c514328cfd2fa10',
    messagingSenderId: '845349142321',
    projectId: 'crt-1-41d13',
    authDomain: 'crt-1-41d13.firebaseapp.com',
    storageBucket: 'crt-1-41d13.appspot.com',
    measurementId: 'G-0ZRET6Y202',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFKz3UOWRFOsfbNINb5Ef7E0iWewpbqzQ',
    appId: '1:845349142321:android:40e3e306bfb9c248d2fa10',
    messagingSenderId: '845349142321',
    projectId: 'crt-1-41d13',
    storageBucket: 'crt-1-41d13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfxp6W14OGx_RUst1Ubt33WSEafheFMfE',
    appId: '1:845349142321:ios:04d323194b4527b2d2fa10',
    messagingSenderId: '845349142321',
    projectId: 'crt-1-41d13',
    storageBucket: 'crt-1-41d13.appspot.com',
    iosBundleId: 'com.example.crp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfxp6W14OGx_RUst1Ubt33WSEafheFMfE',
    appId: '1:845349142321:ios:04d323194b4527b2d2fa10',
    messagingSenderId: '845349142321',
    projectId: 'crt-1-41d13',
    storageBucket: 'crt-1-41d13.appspot.com',
    iosBundleId: 'com.example.crp',
  );
}
